### ISSUE TITLE
kappa not found?

### ISSUE THREAD

**Issue by poulsbopete** [ryansb/hugo-lambda#19]
I just spun up a brand new ubuntu node in EC2, followed the instructions and I can't get past the kappa not found error. Has anyone seen this before? I am using an IAM user, but have given it full admin, removed the SiteDNS so Route53 shouldn't be an issue.... Thank you in advance.

ubuntu@ip:~/hugo-lambda$ make create
Generated CFN template
aws cloudformation create-stack --stack-name HugoSiteStack --template-body file://hugo-lambda.cfn --capabilities CAPABILITY_IAM
{
    "StackId": "arn:aws:cloudformation:us-west-2:[string]:stack/HugoSiteStack/xxx-xxxxx-xxxx-xxxxx-xxxxee6"
}
sleep 120 # wait for the stack to be created, we need the IAM role to exist for the next steps
exec sed -i -e s/EXECROLE/$(aws cloudformation describe-stack-resources --stack-name HugoSiteStack --logical-resource-id ExecRole --query 'StackResources[0].PhysicalResourceId')/ generate/config.yml
cd generate && kappa config.yml create && kappa config.yml add_event_sources
/bin/sh: 1: kappa: not found
make: **\* [create] Error 127

**Comment by ryansb** [comment]
You need to install [kappa](https://github.com/garnaat/kappa) from Github. It's a python helper for working with Lambda.
