### ISSUE TITLE
Deployment ready Hugo site example

### ISSUE THREAD

**Issue by vitr** [ryansb/hugo-lambda#6]
thanks for the great work! this is not an issue, more like a suggestion.
I have difficulties with generating a website from the blog post
http://rsb.io/posts/deploying-hugo-lambda/
I think, something has changed in hugo/docs repo , I've got a blank index page in the end. Which is frustrating, as I was sure that hugo-lambda worked just fine.
I tested it with another random github example and failed again, but third time lucky, tried this https://github.com/ArjenSchwarz/hugo-wercker-ewok-example and bingo! got the webiste.
it would be great if you can include deployment ready site(s) in the hugo-lambda source, so, we don't depend on any 3rd parties for this. If I find any decent and good looking examples, I'm also ready to contribute.

**Comment by ryansb** [comment]
Oh darn - it looks like the latest hugo docs require the latest hugo. I've updated to the latest stable version of hugo in the Makefile, so you can download that as well. 

I'll see about including a demo site so this doesn't happen in the future.
