### ISSUE TITLE
Triggering site generation process

### ISSUE THREAD

**Issue by vitr** [ryansb/hugo-lambda#9]
I'm just wondering, is there a better to trigger the lambda function? Currently it's triggered by input.bucket object creation, which is great for new content, but if you edit existing post, there is no way to regenerate the site.

**Comment by ryansb** [comment]
You can add more triggers, but the `ObjectCreated:*` event type includes POST and PUT ([source](http://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html#notification-how-to-event-types-and-destinations)) events (creation & modification) so the trigger should run on post edits as well.

**Comment by ryansb** [comment]
You can also run `kappa generate/config.yml invoke` and it will trigger the function with the contents of "sample.json". Just change it with the name of your input bucket.

**Comment by ryansb** [comment]
Also, I've added the "make invoke" command so you can invoke a site generation straight from the command line.
